<?php
class MusicDataSeeder extends Seeder
{
	public function run()
	{
		$genres = [
			'Ambient',
			'Ambient dub',
			'Ambient industrial',
			'Ambient house',
			'Dark ambient',
			'Drone music',
			'Isolationism',
			'Breakbeat',
			'Acid breaks',
			'Baltimore club',
			'Big beat',
			'Broken beat',
			'Nu skool breaks',
			'Florida breaks',
			'Nu-funk',
			'Miami bass',
			'Video game music',
			'Chiptune',
			'Bitpop',
			'Bleep techno',
			'Game Boy music',
			'Nintendocore',
			'Skweee',
			'Disco',
			'Cosmic disco',
			'Disco polo',
			'Euro disco',
			'Italo disco',
			'Nu-disco',
			'Space disco',
			'Downtempo',
			'Acid jazz',
			'Chill out',
			'Ethnic electronica',
			'Psybient',
			'New-age music',
			'Nu jazz',
			'Trip hop',
			'Drum and bass',
			'Darkstep',
			'Drumstep',
			'Drill and bass',
			'Drumfunk',
			'Funkstep',
			'Hardstep',
			'Jump-Up',
			'Jazzstep',
			'Liquid funk',
			'Neurofunk',
			'Sambass',
			'Techstep',
			'Dub fusion genres',
			'Afro-dub',
			'Dubstep',
			'Brostep',
			'Post-dubstep',
			'Wonky',
			'Dubstyle',
			'Dubtronica',
			'Electro music',
			'Freestyle music',
			'Electroacoustic music',
			'Acousmatic music',
			'Musique concrète',
			'Electronica',
			'Berlin school',
			'Chillwave',
			'Folktronica',
			'Funktronica',
			'Laptronica',
			'Livetronica',
			'Electronic rock',
			'Alternative dance',
			'Coldwave',
			'Dance-punk',
			'Dark Wave',
			'Electronicore',
			'Ethereal Wave',
			'Indietronica',
			'Krautrock',
			'New rave',
			'Nu-gaze',
			'Space rock',
			'Synthpop',
			'Synthpunk',
			'Hardcore',
			'4-beat',
			'Breakbeat hardcore',
			'Bouncy techno',
			'Breakcore',
			'Digital hardcore',
			'Darkcore',
			'Gabber',
			'Happy hardcore',
			'Makina',
			'Rave',
			'Speedcore',
			'Terrorcore',
			'Trancecore',
			'UK hardcore',
			'Hardstyle',
			'Hard house',
			'Hard bounce',
			'Hard NRG',
			'Nu-NRG',
			'Jumpstyle',
			'Jump House/Melbourne Jump',
			'Lento violento',
			'Hi-NRG',
			'Eurobeat',
			'Eurodance',
			'Bubblegum dance',
			'Italo dance',
			'House music',
			'Acid house',
			'Balearic beat',
			'Chicago house',
			'Deep house',
			'Diva house/Handbag house',
			'Hardbag',
			'Electroclash',
			'Electro house',
			'Complextro',
			'Dutch house',
			'Fidget house',
			'Moombahton',
			'Moombahcore',
			'Electro swing',
			'Swing house',
			'Freestyle house',
			'French house',
			'Funky house',
			'Garage house',
			'Ghetto house',
			'Hip house',
			'Italo house',
			'Kwaito',
			'Latin house',
			'Microhouse/Minimal house',
			'New beat',
			'Progressive house',
			'Big room house',
			'Tech house',
			'Tribal house',
			'Vocal house',
			'Industrial music',
			'Aggrotech',
			'Cybergrind',
			'Electro-industrial',
			'Dark electro',
			'Electronic body music',
			'Futurepop',
			'Industrial metal',
			'Industrial rock',
			'Japanoise',
			'Neue Deutsche Härte',
			'Power electronics',
			'Death industrial',
			'Power noise',
			'Witch house/Drag',
			'IDM',
			'Glitch|Glitch hop',
			'Jungle',
			'Darkcore jungle',
			'Raggacore',
			'Ragga-jungle',
			'Post-disco',
			'Boogie',
			'Dance-pop',
			'Dance-rock',
			'Techno',
			'Acid techno',
			'Detroit techno',
			'Free tekno',
			'Ghettotech',
			'Hardtechno',
			'Minimal techno',
			'Nortec',
			'Rotterdam techno',
			'Schranz',
			'Symphonic techno',
			'Tecno brega',
			'Trance music',
			'Acid trance',
			'Dream trance',
			'Goa trance',
			'Hard trance',
			'Ibiza trance',
			'Nitzhonot',
			'Psychedelic trance',
			'Dark psytrance',
			'Full on',
			'Psybreaks',
			'Suomisaundi',
			'Progressive trance',
			'Tech trance',
			'Uplifting trance',
			'Vocal trance',
			'Trap',
			'Trapstep',
			'UK garage',
			'2-step garage',
			'Breakstep',
			'Future garage/Chillstep',
			'Grime',
			'Grindie',
			'Speed garage',
			'Bassline/4x4 garage',
			'UK funky',
		];

		foreach ($genres as $genreName) {
			$genreData = ['name' => $genreName];
			$genre = MusicGenre::firstOrCreate($genreData);
		}

		$programs = [
			'Reaktor',
			'Max/MSP',
			'Pure Data',
		];

		foreach ($programs as $programName) {
			$programData = ['name' => $programName];
			$program = MusicProgram::firstOrCreate($programData);
		}

		$plugins = [
			[
				'name' => 'reFX Nexus',
				'banks' => [
					'House Vol.1',
					'Dance Orchestra',
					'Perpetual Motion',
					'Dance Drums',
					'Store n’ Forward',
					'Stratosphere',
					'Analog',
					'Bigtone Signature',
					'Guitars',
					'Dance Vol.3',
					'Rauschwerk',
					'Pop',
					'HandsUp-Electro Bass',
					'Vocoder',
					'Vintage DrumKits',
					'HandsUp-Electro Bass Vol.2',
					'Omicron 2',
					'Future Arps',
					'Stratosphere 2',
					'Rauschwerk 2',
					'TV Movie Game',
					'Future Arps 2',
					'Hollywoood',
					'Dubstep-Electro Vol.1',
					'Apres-Ski',
					'Millennium Pop 2',
					'Future Arps 3',
					'HandsUp-Electro Bass Vol. 3',
					'FX',
					'Christmas',
					'Swedish House Vol. 1',
					'Sound oft he 90s',
					'Dubstep-Electro Vol. 2',
					'House Vol. 2',
					'Rauschwerk 3',
					'Hollywood 2',
					'Hardstyle 2',
					'Electro House Leads',
					'Dance Vol 1',
					'Minimal House',
					'Psytrance',
					'Hardstyle',
					'Bass',
					'Total Piano',
					'Minimal House 2',
					'Crank',
					'SID',
					'Dance Vol. 2',
					'Bigtone Signature 2',
					'Omicron',
					'NuElectro',
					'Crank 2',
					'Bigtone Signature 3',
					'ROM Extension',
					'FM',
					'Kamui',
					'Trance Elements',
					'HandsUp Leads Vol 1',
					'Classic Trance',
					'Omicron 3',
					'Millennium Pop',
					'Dark Planet',
					'Kamui 2',
					'Trance Leads',
					'7 Skies Trance',
					'Commercial Electro',
					'Halloween',
					'Hip Hop',
					'Progressive Tech House',
					'Bass 2Freaky Machines',
					'Trance Anthems',
					'Dubstep-Electro Vol.3',
					'Trap',
					'Christmas 2013',
				],
			],
			['name' => 'Vanguard', 'banks' => []],
			['name' => 'Massive', 'banks' => []],
			['name' => 'Sylenth 1', 'banks' => []],
			['name' => 'Sonic Academy’s A.N.A.', 'banks' => []],
			['name' => 'Virus TI 2', 'banks' => []],
			['name' => 'MONARK', 'banks' => []],
			['name' => 'ABSYNTH 5', 'banks' => []],
			['name' => 'FM8', 'banks' => []],
			['name' => 'REAKTOR PRISM', 'banks' => []],
			['name' => 'REAKTOR SPARK', 'banks' => []],
			['name' => 'RETRO MACHINES MK 2', 'banks' => []],
			['name' => 'VIENNA CONCERT GRAND', 'banks' => []],
			['name' => 'UPRIGHT PIANO', 'banks' => []],
			['name' => 'NEW YORK CONCERT GRAND', 'banks' => []],
			['name' => 'BERLIN CONCERT GRAND', 'banks' => []],
			['name' => 'SCARBEE CLAVINET/PIANET', 'banks' => []],
			['name' => 'SCARBEE MARK I', 'banks' => []],
			['name' => 'SCARBEE A-200', 'banks' => []],
			['name' => 'VINTAGE ORGANS', 'banks' => []],
			['name' => 'SESSION STRINGS', 'banks' => []],
			['name' => 'THE GIANT', 'banks' => []],
			['name' => 'WEST AFRICA', 'banks' => []],
			['name' => 'STUDIO DRUMMER', 'banks' => []],
			['name' => 'ABBEY ROAD 60s DRUMMER', 'banks' => []],
			['name' => 'BATTERY 4', 'banks' => []],
			['name' => 'Roland Gaia', 'banks' => []],
			['name' => 'Roland SH-201', 'banks' => []],
			['name' => 'V-Station', 'banks' => []],
			['name' => 'Z3ta+ 2', 'banks' => []],
			['name' => 'JP6K', 'banks' => []],
		];

		foreach ($plugins as $pluginData) {
			$banks = array_pull($pluginData, 'banks');

			$plugin = MusicPlugin::firstOrCreate($pluginData);

			foreach ($banks as $bankName) {
				$bank = MusicPluginBank::firstOrCreate([
					'name' => $bankName,
					'music_plugin_id' => $plugin->id,
				]);
			}
		}
	}
}
